"""
MediMind AI - Personal Healthcare Navigation Agent
Main entry point for the multi-agent system
Multi-Agent Implementation
"""

import sys
from typing import Dict, Any  # ← ADD THIS LINE
from src.agents.orchestrator import OrchestratorAgent
from src.memory.session_manager import SessionManager
from src.memory.memory_bank import MemoryBank
from src.utils.logger import get_logger
from src.config import Config

logger = get_logger(__name__)

class MediMindAI:
    """Main application class for MediMind AI"""
    
    def __init__(self):
        """Initialize MediMind AI with all components"""
        logger.info("Initializing MediMind AI...")
        
        # Initialize orchestrator (which initializes all sub-agents)
        self.orchestrator = OrchestratorAgent()
        
        # Initialize memory systems
        self.session_manager = SessionManager()
        self.memory_bank = MemoryBank()
        
        logger.info("MediMind AI initialized successfully")
    
    def run(self):
        """Run the main conversation loop"""
        self._print_welcome()
        
        while True:
            try:
                # Get user input
                user_input = input("\n👤 You: ").strip()
                
                # Check for exit commands
                if user_input.lower() in ['quit', 'exit', 'bye']:
                    self._handle_exit()
                    break
                
                if not user_input:
                    continue
                
                # Add user message to session
                self.session_manager.add_message("user", user_input)
                
                # Get current context
                context = self.session_manager.get_context()
                
                # Process through orchestrator
                result = self.orchestrator.process(user_input, context)
                
                # Extract response
                response = result.get("response", "I apologize, I couldn't process that.")
                agent_name = result.get("agent", "Unknown")
                
                # Update context based on result
                self._update_context(result)
                
                # Add assistant response to session
                self.session_manager.add_message("model", response)
                
                # Display response
                print(f"\n🤖 MediMind ({agent_name}): {response}")
                
                # Log agent used
                logger.info(f"Response generated by: {agent_name}")
                
            except KeyboardInterrupt:
                print("\n\nInterrupted by user")
                self._handle_exit()
                break
            except Exception as e:
                logger.error(f"Error in main loop: {str(e)}")
                print(f"\n❌ An error occurred: {str(e)}")
                print("Please try again or type 'quit' to exit.")
    
    def _update_context(self, result: Dict):
        """Update session context based on agent result"""
        
        # Add medications if found
        for med in result.get("medications_mentioned", []):
            self.session_manager.add_medication(med)
        
        # Add symptoms if discussed
        # (Could extract from symptom agent response)
        
    def _print_welcome(self):
        """Print welcome message"""
        print("=" * 60)
        print("🏥 MediMind AI - Personal Healthcare Assistant")
        print("=" * 60)
        print(f"✅ Multi-Agent System Active")
        print(f"✅ Agents: Symptom Analyzer, Medication Manager, Doctor Prep")
        print(f"✅ Memory Bank: Enabled")
        print("\nType 'quit' to exit")
        print("-" * 60)
    
    def _handle_exit(self):
        """Handle application exit"""
        print("\n💾 Saving session to memory...")
        
        # Save session to long-term memory
        session_data = self.session_manager.get_context()
        self.memory_bank.save_session(session_data)
        
        print("✅ Session saved!")
        print("\n👋 Take care of your health! Goodbye!")
        logger.info("Application exited normally")

def main():
    """Main entry point"""
    try:
        app = MediMindAI()
        app.run()
    except Exception as e:
        logger.error(f"Fatal error: {str(e)}")
        print(f"\n❌ Fatal error: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()